-- Create contact_submissions table
CREATE TABLE IF NOT EXISTS contact_submissions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  name TEXT NOT NULL,
  email TEXT NOT NULL,
  message TEXT NOT NULL
);

-- Enable Row Level Security
ALTER TABLE contact_submissions ENABLE ROW LEVEL SECURITY;

-- Create policy to allow anonymous inserts (for the contact form)
CREATE POLICY "Allow anonymous inserts" ON contact_submissions
  FOR INSERT
  TO anon
  WITH CHECK (true);

-- Create policy to allow service role to view all (for admin dashboard if needed)
CREATE POLICY "Allow service role to view all" ON contact_submissions
  FOR SELECT
  TO service_role
  USING (true);

-- Insert dummy data
INSERT INTO contact_submissions (name, email, message, created_at)
VALUES
  ('Alice Johnson', 'alice@example.com', 'I am interested in your web development services. Can we schedule a call?', NOW() - INTERVAL '2 days'),
  ('Bob Smith', 'bob@example.com', 'Do you offer SEO audits? My website traffic has been dropping.', NOW() - INTERVAL '5 days'),
  ('Charlie Brown', 'charlie@example.com', 'Great work on the new design! Just wanted to say thanks.', NOW() - INTERVAL '1 week'),
  ('Diana Prince', 'diana@example.com', 'I need a quote for a custom e-commerce platform.', NOW() - INTERVAL '2 weeks');
